### ISSUE TITLE
The compilation of XtxtUML xtend files fails with NullPointerException

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#106]
Running txtUML in a runtime Eclipse produces the following errors:

(All NullPointerExceptions occurred at the same line, I only copied the first stack trace.)

1    [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/formatting/XtxtUMLFormatter.xtend'.
java.lang.NullPointerException
	at org.eclipse.core.runtime.Path.append(Path.java:261)
	at org.eclipse.xtext.builder.JDTAwareEclipseResourceFileSystemAccess2.addToSourceFolders(JDTAwareEclipseResourceFileSystemAccess2.java:66)
	at org.eclipse.xtend.ide.builder.SourceRelativeFileSystemAccess.ensureOutputConfigurationDirectoryExists(SourceRelativeFileSystemAccess.java:29)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:259)
	at org.eclipse.xtext.generator.AbstractFileSystemAccess2.generateFile(AbstractFileSystemAccess2.java:28)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$7.apply(ParallelFileSystemAccess.java:141)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$7.apply(ParallelFileSystemAccess.java:1)
	at org.eclipse.xtext.builder.ParallelFileSystemAccess$1.apply(ParallelFileSystemAccess.java:57)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doBuild(ParallelBuilderParticipant.java:128)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:221)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:252)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
14   [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/labeling/XtxtUMLDescriptionLabelProvider.xtend'.
java.lang.NullPointerException
    ...
16   [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/contentassist/XtxtUMLProposalProvider.xtend'.
java.lang.NullPointerException
	...
33   [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLEarlyExitComputer.xtend'.
java.lang.NullPointerException
	...
35   [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/scoping/XtxtUMLImplicitlyImportedFeatures.xtend'.
java.lang.NullPointerException
	...
37   [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/outline/XtxtUMLOutlineTreeProvider.xtend'.
java.lang.NullPointerException
	...
177  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/quickfix/XtxtUMLQuickfixProvider.xtend'.
java.lang.NullPointerException
	...
181  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/jvmmodel/XtxtUMLJvmModelInferrer.xtend'.
java.lang.NullPointerException
	...
182  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/validation/XtxtUMLValidator.xtend'.
java.lang.NullPointerException
	...
188  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/scoping/XtxtUMLXImportSectionNamespaceScopeProvider.xtend'.
java.lang.NullPointerException
	...
191  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/naming/XtxtUMLQualifiedNameConverter.xtend'.
java.lang.NullPointerException
	...
193  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/compiler/XtxtUMLCompiler.xtend'.
java.lang.NullPointerException
	...
203  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/highlighting/XtxtUMLHighlightingCalculator.xtend'.
java.lang.NullPointerException
	...
205  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link10/hu/elte/txtuml/xtxtuml/typesystem/XtxtUMLTypeComputer.xtend'.
java.lang.NullPointerException
	...
221  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link9/hu/elte/txtuml/xtxtuml/lib/std.xtend'.
java.lang.NullPointerException
    ...
222  [Worker-5] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/.org.eclipse.jdt.core.external.folders/.link11/hu/elte/txtuml/xtxtuml/ui/labeling/XtxtUMLLabelProvider.xtend'.
java.lang.NullPointerException
    ...

**Comment by kovacsgabor** [comment]
Deleting and recreating my workspace solved the problem.
