### ISSUE TITLE
C++ export error

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#402]
Stack trace:
```
index=0, size=0
index=0, size=0
  org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
  	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createReadLinkActionCode(ActivityExporter.java:289)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createActivityNodeCode(ActivityExporter.java:223)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createActivityNodeCode(ActivityExporter.java:207)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createActivityPartCode(ActivityExporter.java:172)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createActivityPartCode(ActivityExporter.java:154)
  	at hu.elte.txtuml.export.cpp.ActivityExporter.createfunctionBody(ActivityExporter.java:109)
  	at hu.elte.txtuml.export.cpp.ClassExporter.createFuncTypeMap(ClassExporter.java:378)
  	at hu.elte.txtuml.export.cpp.ClassExporter.createSource(ClassExporter.java:93)
  	at hu.elte.txtuml.export.cpp.Uml2ToCppExporter.buildCppCode(Uml2ToCppExporter.java:97)
  	at hu.elte.txtuml.export.cpp.wizardz.TxtUMLToCppGovernor.uml2ToCpp(TxtUMLToCppGovernor.java:85)
```

**Comment by nboldi** [comment]
Exporting the MoonLander model

**Comment by nboldi** [comment]
The problem was in the model export
