### ISSUE TITLE
NullPointerException on model export

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#44]
The performance test model produces that. There is a validation error in the model, and there are invalid files, but the error is not caused by neither of them.

```
java.lang.NullPointerException
  java.lang.NullPointerException
  	at hu.elte.txtuml.export.uml2.transform.exporters.expressions.ExpressionExporter.createCallOperationAction(ExpressionExporter.java:280)
  	at hu.elte.txtuml.export.uml2.transform.exporters.expressions.OperatorExporter.export(OperatorExporter.java:33)
  	at hu.elte.txtuml.export.uml2.transform.exporters.expressions.OperatorExporter.exportRaw(OperatorExporter.java:25)
  	at hu.elte.txtuml.export.uml2.transform.exporters.expressions.ExpressionVisitor.visit(ExpressionVisitor.java:140)
  	at org.eclipse.jdt.core.dom.InfixExpression.accept0(InfixExpression.java:365)
  	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
  	at hu.elte.txtuml.export.uml2.transform.exporters.expressions.ExpressionExporter.export(ExpressionExporter.java:94)
  	at hu.elte.txtuml.export.uml2.transform.exporters.controls.IfActionExporter.exportIfStatement(IfActionExporter.java:45)
  	at hu.elte.txtuml.export.uml2.transform.visitors.BlockVisitor.visit(BlockVisitor.java:84)
  	at org.eclipse.jdt.core.dom.IfStatement.accept0(IfStatement.java:187)
  	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
  	at hu.elte.txtuml.export.uml2.transform.exporters.BlockExporter.lambda$0(BlockExporter.java:93)
  	at hu.elte.txtuml.export.uml2.transform.exporters.BlockExporter$$Lambda$31/1922254984.accept(Unknown Source)
  	at java.lang.Iterable.forEach(Iterable.java:75)
  	at hu.elte.txtuml.export.uml2.transform.exporters.BlockExporter.export(BlockExporter.java:92)
  	at hu.elte.txtuml.export.uml2.transform.exporters.BlockExporter.exportBody(BlockExporter.java:65)
  	at hu.elte.txtuml.export.uml2.transform.exporters.MethodBodyExporter.exportMethodBody(MethodBodyExporter.java:46)
  	at hu.elte.txtuml.export.uml2.transform.exporters.MethodBodyExporter.export(MethodBodyExporter.java:32)
  	at hu.elte.txtuml.export.uml2.transform.exporters.MethodBodyExporter.export(MethodBodyExporter.java:25)
  	at hu.elte.txtuml.export.uml2.transform.exporters.VertexExporter.exportStateEntryAction(VertexExporter.java:93)
  	at hu.elte.txtuml.export.uml2.transform.exporters.VertexExporter.exportVertex(VertexExporter.java:47)
  	at hu.elte.txtuml.export.uml2.transform.visitors.VertexVisitor.visit(VertexVisitor.java:29)
  	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
  	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
  	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
  	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
  	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
  	at hu.elte.txtuml.export.uml2.transform.exporters.RegionExporter.exportVertices(RegionExporter.java:28)
  	at hu.elte.txtuml.export.uml2.transform.exporters.RegionExporter.exportRegion(RegionExporter.java:20)
  	at hu.elte.txtuml.export.uml2.transform.exporters.ModelExporter.exportStateMachine(ModelExporter.java:316)
  	at hu.elte.txtuml.export.uml2.transform.exporters.ModelExporter.lambda$2(ModelExporter.java:304)
  	at hu.elte.txtuml.export.uml2.transform.exporters.ModelExporter$$Lambda$30/881901549.accept(Unknown Source)
  	at java.util.HashMap.forEach(HashMap.java:1280)
  	at hu.elte.txtuml.export.uml2.transform.exporters.ModelExporter.exportStateMachinesOfEveryClass(ModelExporter.java:302)
  	at hu.elte.txtuml.export.uml2.transform.exporters.ModelExporter.exportModel(ModelExporter.java:181)
  	at hu.elte.txtuml.export.uml2.UML2.exportModel(UML2.java:107)
  	at hu.elte.txtuml.export.uml2.UML2.exportModel(UML2.java:58)
  	at hu.elte.txtuml.export.ExportUtils.exportTxtUMLModelToUML2(ExportUtils.java:31)
  	at hu.elte.txtuml.export.papyrus.wizardz.TxtUMLVisuzalizeWizard$1.run(TxtUMLVisuzalizeWizard.java:109)
  	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
  	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
  	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:527)
  	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:284)
  	at org.eclipse.ui.internal.progress.ProgressManager.run(ProgressManager.java:1190)
  	at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1380)
  	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
  	at org.eclipse.ui.internal.progress.ProgressManager$5.run(ProgressManager.java:1214)
  	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)
  	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:156)
  	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4734)
  	at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:1211)
  	at hu.elte.txtuml.export.papyrus.wizardz.TxtUMLVisuzalizeWizard.performFinish(TxtUMLVisuzalizeWizard.java:89)
  	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:853)
  	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:438)
  	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
  	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
  	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
  	at org.eclipse.jface.window.Window.open(Window.java:808)
  	at hu.elte.txtuml.export.papyrus.handlers.TxtUMLVisualizeHandler.execute(TxtUMLVisualizeHandler.java:27)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:825)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:701)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$6(HandledContributionItem.java:685)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:613)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
  	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
  	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by kovacsgabor** [comment]
The problem is caused by the following code:
```java
A a = assoc(AB.a.class).selectAny();
if (a != null) {
  // ...
}
```
As the current exportation only supports operators used on primitive types.

**Comment by kovacsgabor** [comment]
I would like to note that the null check is unnecessary here, as the result of the assoc() method is a collection, which has the isEmpty method. So the following solution works fine:

```java
Collection<A> coll = assoc(AB.a.class);
if (!coll.isEmpty()) {
  A a = coll.selectAny();
  // ...
}
```

I think this is a clearer solution.

**Comment by kovacsgabor** [comment]
A temporary solution is now implemented. A better support for object equality and inequality checks might be needed in the future.

**Comment by kovacsgabor** [comment]
Opened new issue: #47
