### ISSUE TITLE
XtxtUML editor throws nullptr exception

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#96]
~~~
2542841 [Worker-4] ERROR org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder  - Error initializing JvmElement
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReferenceFactory.toPlainTypeReference(LightweightTypeReferenceFactory.java:117)
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.toPlainTypeReference(StandardTypeReferenceOwner.java:108)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypeReferenceBuilder.typeRef(JvmTypeReferenceBuilder.java:112)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.lambda$19(XtxtUMLJvmModelInferrer.java:523)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.lambda$15(XtxtUMLJvmModelInferrer.java:526)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.toAnnotationRef(XtxtUMLJvmModelInferrer.java:529)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer._toAnnotationRef(XtxtUMLJvmModelInferrer.java:508)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.toAnnotationRef(XtxtUMLJvmModelInferrer.java:746)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.lambda$11(XtxtUMLJvmModelInferrer.java:411)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:206)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toClass(JvmTypesBuilder.java:384)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer._toJvmMember(XtxtUMLJvmModelInferrer.java:422)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.toJvmMember(XtxtUMLJvmModelInferrer.java:725)
	at hu.elte.txtuml.xtxtuml.jvmmodel.XtxtUMLJvmModelInferrer.lambda$3(XtxtUMLJvmModelInferrer.java:219)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:397)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:407)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:240)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareBatchTypeResolver.getEntryPoints(LogicalContainerAwareBatchTypeResolver.java:44)
	at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver.getTypeResolver(DefaultBatchTypeResolver.java:63)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:49)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$1.get(CachingBatchTypeResolver.java:1)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:46)
	at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
	at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:71)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.resolveLazyCrossReferences(BatchLinkableResource.java:165)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:528)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:234)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:115)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:248)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:228)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:123)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
~~~

**Comment by devaigergely81** [comment]
It was probably connected to
https://github.com/ELTE-Soft/txtUML/pull/89#issuecomment-152130319
I have not experienced the above exception and workbench freeze after the erroneous fix for #25 was reverted.

**Comment by devaigergely81** [comment]
It turns out it was not connected to #89. The editor does not freeze now, but the exception mentioned above is still thrown sometimes.

**Comment by djnemeth** [comment]
I haven't managed to reproduce the issue yet. Could you please provide some additional details about the circumstances of the occurrence of the exception?

**Comment by balintkiss501** [comment]
I've just contacted this bug with the same exception stacktrace. Happened to me, when for example I started changing some state variable names by hand or wanted to write a composite state with the XtxtUML editor.

**Comment by djnemeth** [comment]
Unfortunately, I could not reproduce this issue. Hopefully it got fixed since November, as some parts of the model inferrer (including the problematic annotation reference generation) have been rewritten as part of #280 (especially in 56571ea).
